# config/doctrine/mapping/Job.orm.yml
App\Entity\Job:
  type: entity
  repositoryClass: App\Repository\JobRepository

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    type:
      type: string
      length: 255
      nullable: true

    company:
      type: string
      length: 255

    logo:
      type: string
      length: 255
      nullable: true

    url:
      type: string
      length: 255
      nullable: true

    position:
      type: string
      length: 255

    location:
      type: string
      length: 255

    description:
      type: text

    howToApply:
      type: text

    token:
      type: string
      length: 255
      unique: true

    isPublic:
      type: boolean
      default: false

    isActivated:
      type: boolean
      default: true

    email:
      type: string
      length: 255

    expiresAt:
      type: datetime

    createdAt:
      type: datetime

    updatedAt:
      type: datetime
      nullable: true

  #relation de type un vers plusieurs
  manyToOne:
    category:
      targetEntity: Category
      inversedBy: jobs
      joinColumn:
        name: category_id
        referencedColumnName: id


  lifecycleCallbacks:
    prePersist: [setCreatedAtValue, setExpiresAtValue] #appelé lors de la création de l'entité (quand il y a une date)
    preUpdate: [setUpdatedAtValue]  #appelé lors de la mise à jour de l'entité (quand il y a une date)
